In [1]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created:\n",a)

Array created:
 [[1 2 4]
 [5 8 7]]


In [2]:
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
c=np.full((3,3),6)
print("Array with all 6S:\n",c)

Array with all 6S:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [4]:
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.5516059  0.21704829]
 [0.71387749 0.07496801]]


In [5]:
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [6]:
#Reshaping 3x4 array to 2x2x3 array
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [7]:
#flatten array
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("\nFlattened array:\n",flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\nNo.of dimensions:\n",arr.ndim)
print("\nShape of array:\n",arr.shape)
print("\nSize of array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nConverted array element:\n",newtype)
print("\nConverted Array type:\n",newtype.dtype)


No.of dimensions:
 2

Shape of array:
 (3, 4)

Size of array:
 12

Array type:
 int32

Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted Array type:
 float32


In [9]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
