In [8]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a)
print(b)
print("\nVector addition")
print(a+b)
print("\nVector subtraction")
print(a-b)
print("\nVector multiplication")
print(a*b)
print("\nVector division")
print(a/b)
print("\nVector dot product")
print(a.dot(b))
print("nScalar multiplication")
sclr=5
print("sclar value=",sclr)
print("array=",a)
print("result=",a*sclr)
#Numpy.Vectorize method
def my_func(x,y):
#"Return x-y if x>y,otherwise return x+y"
          if x>y:
           return x-y
          else:
           return x+y
print("\n\nNumpy.Vectorize method")
print("(Return x-y if x.y,otherwise return x+y)")
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("array1:",arr1)
print("array2:",arr2)
print("result:",vec_func(arr1,arr2))































Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

Vector addition
[12 24 35 48 60]

Vector subtraction
[ 8 16 25 32 40]

Vector multiplication
[ 20  80 150 320 500]

Vector division
[5. 5. 6. 5. 5.]

Vector dot product
1070
nScalar multiplication
sclar value= 5
array= [10 20 30 40 50]
result= [ 50 100 150 200 250]


Numpy.Vectorize method
(Return x-y if x.y,otherwise return x+y)
array1: [10, 4, 20]
array2: [2, 3, 30]
result: [ 8  1 50]
